### ISSUE TITLE
Coach should only be able to click on the teams they coach. 

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#18]
c_coach1 is coaching only TeamBit and Team3. So, he shouldn't be able to click on TeamWanchester when seeing the profile of p_exon. 

- Should show the error messages. Or does not allow the coach to click on the team that they do not coach. 
- Expect an error like this:
{
    "name": "Error",
    "error": "e400.12: You (username c_coach1) are not associated with requested team TeamWanchester"
}

**Comment by duyreus3105** [comment]
done
