### ISSUE TITLE
Team page shall show the training sessions list of that team.

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#19]
The team page shall show the training sessions list of that team.
Just like on the homepage showing the training sessions list of players.

The sample API to get training sessions for a team is: 
/trainingSessions?teamName=TeamBit

Example:
![sessionsFromTeam](https://user-images.githubusercontent.com/73268574/188151553-87106326-424f-4728-b14b-103bdae22a2c.png)

More details of the API above are in Postman, under the "trainingSessionss from team" collection

**Comment by ThanhNhan2002** [comment]
![sessionsFromTeam](https://user-images.githubusercontent.com/73268574/188151464-9d6ab1b2-5b4b-4ae8-a566-1688a8e462a6.png)

**Comment by duyreus3105** [comment]
done
