### ISSUE TITLE
Major 3: The breadcrumb is duplicated.

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#33]
If you are logging in as a coach and you try to see the profile of a player, then there is 2 breadcrumbs appearing. There should be 1 breadcrumb only. 
![image](https://user-images.githubusercontent.com/73268574/192440878-e329aa49-3c6f-49c4-bf13-5edd96e913bf.png)

**Comment by duyreus3105** [comment]
done
