### ISSUE TITLE
Major 4: coach should be able to see the stats of players in his team

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#34]
coach1 must be able to see the stat of Exon. Right now it throws an error when I am trying to see it.
![image](https://user-images.githubusercontent.com/73268574/192441199-05736cd7-d4ec-4bf8-b321-717773e65cf0.png)

**Comment by duyreus3105** [comment]
done

**Comment by duyreus3105** [comment]
should have seen it right now
