### ISSUE TITLE
Major 5: throws an error, dont show "loading"

### ISSUE THREAD

**Issue by ThanhNhan2002** [Wanchester/sd-front#35]
coach1 cannot see the session NULL 24/4/22, you should return an error in this case.  Right now, it let the page keep loading.
![image](https://user-images.githubusercontent.com/73268574/192441611-6a8ff477-a5c0-41c3-a457-a73aa83360a1.png)

**Comment by duyreus3105** [comment]
I basically remove everything from view if that session does not belong to the team he coaching 
so this is basically sovled

**Comment by ThanhNhan2002** [comment]
Checked, coach1 cannot see NULL 24/4/22 now
